#!/bin/bash

# Detects which OS and if it is Linux then it will detect which Linux Distribution.
if [ -e /etc/os-release ]; then
    . /etc/os-release
else
    echo "Unknown Distribution."
    exit -1
fi


# Main
main() {
    OH_MY_HOME_DIR = "$HOME/.oh-my-home/"

    cd "$HOME"

    sudo apt-get install -y curl git
    curl "https://bootstrap.pypa.io/get-pip.py" | sudo python
    #sudo pip install ansible
    sudo add-apt-repository ppa:ansible/ansible -y
    sudo apt-get update && sudo apt-get install -y ansible

    if [ -d "$OH_MY_HOME_DIR" ]; then
        echo "$OH_MY_HOME_DIR is existed, skip to retrieve."
    else
        echo "$OH_MY_HOME_DIR is not existed, try to retrieve."
        git clone "https://github.com/elleryq/oh-my-home.git" "$OH_MY_HOME_DIR"
    fi
    cd "$OH_MY_HOME_DIR"
    ansible-playbook playbook.yml -c local -i "localhost,"
}

main

exit 0
