#!/bin/sh

# Detects which OS and if it is Linux then it will detect which Linux Distribution.
if [ -e /etc/os-release ]; then
    . /etc/os-release
else
    echo "Unknown Distribution."
    exit -1
fi

install_git_in_debian_based() {
    status=$(dpkg-query -W -f='${Status}\n' git)
    if [ "$status" == "install ok installed"]; then
        echo "git is installed."
    else
        sudo apt-get install -y git
    fi
}

install_git_in_arch() {
    sudo pacman -Syu git
}

install_git() {
    echo "install git"
    case $ID in
        ubuntu|debian|raspbian)
            install_git_in_debian_based
            ;;
        arch)
            install_git_in_arch
            ;;
    esac
}

install_pyenv() {
    git clone https://github.com/yyuu/pyenv.git $HOME/.pyenv
}

# Main
main() {
    cd $HOME

    GIT=$(which git)
    if [ -z "$GIT" ]; then
        install_git
    fi

    OH_MY_HOME=$HOME/.oh-my-home
    git clone https://github.com/elleryq/oh-my-home.git $OH_MY_HOME

    if [ -d $OH_MY_HOME ]; then
        # 
        if [ -d "$OH_MY_HOME/distro/$ID_LIKE" ]; then
            . $OH_MY_HOME/distro/$ID_LIKE
        fi
        # partial 
        if [ -d "$OH_MY_HOME/distro/$ID" ]; then
            . $OH_MY_HOME/distro/$ID
        fi

        ZSH=$(which zsh)
        if [ -z "$ZSH" ]; then
            echo "install zsh"
            install_zsh
        fi

        ln -s $OH_MY_HOME/zshenv $HOME/.zshenv
        ln -s $OH_MY_HOME/zshrc $HOME/.zshrc

        git clone https://github.com/robbyrussell/oh-my-zsh.git .oh-my-zsh
    else
        echo "Cannot 'get oh-my-home', install failed."
        exit -1
    fi

    install_pyenv
    install_packages

    echo "done.  You need to re-open terminal to activate."
}

main

exit 0
