- hosts: all
  roles:
    - cron-apt
  tasks:
    - name: Use latest git
      become: True
      apt_repository: repo='ppa:git-core/ppa'
    - name: Install git
      become: True
      apt: update_cache=yes pkg={{ item }}
      with_items:
        - libcurl4-gnutls-dev
        - libexpat1-dev
        - gettext
        - libssl-dev
        - build-essential
        - git
        - tig
        - zsh
        - tmux
        - cscope
        - ctags
        - gawk
        - vim
        - parcellite
        - terminator
        - meld
        - x-tile
        - pavucontrol
        - silversearcher-ag
        - language-pack-zh-hant
        - fonts-noto
        - fonts-noto-cjk
        - fonts-noto-hinted
        - fonts-noto-unhinted
    - name: Install beautify_bash
      become: True
      get_url: url=http://arachnoid.com/python/python_programs/beautify_bash.py dest=/usr/local/bin/beautify_bash mode=0755
    - name: setup zsh
      file: path={{ item.path }} state={{ item.state }}
      with_items:
        - { path: "~/.zshenv", state: "absent" }
        - { path: "~/.zshrc", state: "absent" }
    - file: src={{ item.src }} dest={{ item.dest }} state={{ item.state }}
      with_items:
          - { src: "{{ OH_MY_HOME }}/zshenv", dest: "~/.zshenv", state: "link" }
          - { src: "{{ OH_MY_HOME }}/zshrc", dest: "~/.zshrc", state: "link" }
    - git: repo=https://github.com/robbyrussell/oh-my-zsh.git
           dest={{ OH_MY_ZSH }}
    - name: Install tmux
      file: path=~/.tmux.conf state="absent"
    - file: src="{{ OH_MY_HOME }}/tmux.conf" dest="~/.tmux.conf" state="link"
    - name: Install pyenv
      git: repo=https://github.com/yyuu/pyenv.git
           dest=~/.pyenv
    - name: Install gcin
      become: True
      apt_key: keyserver=keyserver.ubuntu.com id=835AB0E3 state=present
#    - apt_repository: repo="deb http://www.csie.nctu.edu.tw/~cp76/gcin/download/debian eliu release" state=present update_cache=yes
    - apt_repository: repo="deb http://hyperrate.com/debian eliu release" state=present update_cache=yes
      become: True
    - apt: pkg=gcin
      become: True
    - file: path="{{EXVIM}}" state=absent
    - name: Install exvim
      git: repo=https://github.com/elleryq/exvim.git
           dest="{{EXVIM}}"
    - file: src="{{EXVIM}}/{{ item }}" dest="{{ansible_env.HOME}}/{{item}}" state=link
      with_items:
          - .vimrc
          - .vimrc.local
          - .vimrc.plugins
          - .vimrc.plugins.local
    - file: src="{{EXVIM}}/vimfiles" dest="{{ansible_env.HOME}}/.vim" state=link
    - name: Install vim plugins
      shell: sh "{{EXVIM}}/unix/install.sh"
      args:
        chdir: "{{ EXVIM }}"
    - shell: vim -u .vimrc --cmd "set rtp=./vimfiles,\$VIMRUNTIME,./vimfiles/after" +PluginInstall +qall
      args:
        chdir: "{{ EXVIM }}"
    - name: Set git default editor
      command: git config --global core.editor vim

  vars:
    - OH_MY_HOME: "{{ ansible_env.HOME }}/.oh-my-home"
    - OH_MY_ZSH: "{{ ansible_env.HOME }}/.oh-my-zsh"
    - EXVIM: "{{ ansible_env.HOME }}/exvim"
