---
# - name: Setup APT proxy configuration
  # sudo: yes
  # template: src={{item.src}} dest={{item.dest}} mode={{item.mode}}
  # with_items:
    # - { src: 'apt-conf-detect-proxy.j2', dest: '/etc/apt/apt.conf.d/30detectproxy', mode: '0644' }
    # - { src: 'detect-http-proxy.j2', dest: '/etc/apt/detect-http-proxy', mode: '0755' }
- name: Install useful packages
  sudo: yes
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - iputils-tracepath
    - glances
    - htop
    - tmux
